'use client';

import { useAdminAnalytics } from '../hooks/use-admin-analytics';
import { AdminMetricCard } from './AdminMetricCard';
import { RecommendationStrategyTable } from './RecommendationStrategyTable';
import { AdminLoadingState } from './AdminLoadingState';
import { AdminErrorState } from './AdminErrorState';
import { Sparkles, MousePointerClick, ShoppingBag, DollarSign } from 'lucide-react';

export function RecommendationAnalytics() {
  const { strategyMetrics, totals, isLoading, isError, refetch } = useAdminAnalytics();

  if (isLoading) return <AdminLoadingState />;
  if (isError) return <AdminErrorState message="Failed to load recommendation analytics data." onRetry={refetch} />;

  return (
    <div className="space-y-8">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <AdminMetricCard
          title="Total Impressions"
          value={totals.impressions.toLocaleString()}
          icon={Sparkles}
          description="Total recommendation card impressions"
          accentColor="primary"
        />
        <AdminMetricCard
          title="Total Recommendation Clicks"
          value={totals.clicks.toLocaleString()}
          icon={MousePointerClick}
          trend={{ value: `${(totals.averageCTR * 100).toFixed(2)}% CTR`, isPositive: true }}
          description="User clicks on recommended products"
          accentColor="info"
        />
        <AdminMetricCard
          title="Attributed Purchases"
          value={totals.conversions.toLocaleString()}
          icon={ShoppingBag}
          trend={{ value: `${(totals.averageConversionRate * 100).toFixed(2)}% Conv`, isPositive: true }}
          description="Purchases originating from AI recommendations"
          accentColor="success"
        />
        <AdminMetricCard
          title="Attributed Simulated Revenue"
          value={`$${totals.revenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`}
          icon={DollarSign}
          description="Estimated revenue generated by engine"
          accentColor="warning"
        />
      </div>

      {/* Strategy Table */}
      <div className="space-y-4">
        <div>
          <h2 className="text-base font-bold text-foreground">Recommendation Strategy Breakdown</h2>
          <p className="text-xs text-muted-foreground">
            Performance comparison across all 9 deterministic recommendation engine strategies.
          </p>
        </div>

        <RecommendationStrategyTable metrics={strategyMetrics} />
      </div>
    </div>
  );
}
